mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:root}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL:127.0.0.1:3306}


spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
