amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

keycloak:
  realm: test
  host: http://test:8443

mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: 127.0.0.1:${mysql.port}


spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration